---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.16

inputs:
  - name: dp-api-router
    path: dp-api-router

outputs:
  - name: build

run:
  path: dp-api-router/ci/scripts/build.sh
